# NUMPY BASICS

In [3]:
import numpy as np

In [7]:
#n-dimensional-array

np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
np1.shape

(10,)

In [13]:
np2 = np.arange(10)
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np3 = np.arange(0,10,3)
np3

array([0, 3, 6, 9])

In [17]:
# creating a array of zeroes
np4 = np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
#2d array
np5 = np.zeros((2,10))
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np6 = np.full((10),6)
np6

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [21]:
np7 = np.full((2,10),7)
np7

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [22]:
#converting python list to numpy array
l = [1,2,3,4,5]
np8 = np.array(l)
np8

array([1, 2, 3, 4, 5])

In [24]:
#slicing numpy array
s1 = np.array([1,2,3,4,5,6,7,8,9])
print(s1[1:5])

[2 3 4 5]


In [25]:
#return from something till the end
print(s1[3:])

[4 5 6 7 8 9]


In [27]:
#using negative index
print(s1[-3:-1])

[7 8]


In [28]:
#slicing with steps
print(s1[1:5:2])

[2 4]


In [30]:
s2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(s2[1,2])

8


In [32]:
print(s2[0:1,1:3])

[[2 3]]


In [33]:
print(s2[0:2, 1:3])

[[2 3]
 [7 8]]


In [36]:
#universal functions in numpy
u1 = np.array([0,-1,2,-3,4,5,6,7,-8,-9])
print(u1)

[ 0 -1  2 -3  4  5  6  7 -8 -9]


In [ ]:
#square root of each element
s = np.sqrt(u1)
# absolute value
ab = np.absolute(u1)
#exponents
ex = np.exp(u1)
# Min\Max
m = np.max(u1)
#sign
si = np.sign(u1)
# trig
t = np.sin(u1)
#log
l = np.log(u1)

In [40]:
#copy vs view
np1 = np.array([0,1,2,3,4,5])
np2 = np1.view()
print(f'original np1:{np1}')
print(f'Original np2:{np2}')

original np1:[0 1 2 3 4 5]
Original np2:[0 1 2 3 4 5]


In [41]:
np1[0] = 41
print(f'changed np1:{np1}')
print(f'Original np2:{np2}')

changed np1:[41  1  2  3  4  5]
Original np2:[41  1  2  3  4  5]


In [43]:
np3 = np1.copy()
print(f'oiginal np1:{np1}')
print(f'Original np3:{np3}')

changed np1:[41  1  2  3  4  5]
Original np3:[41  1  2  3  4  5]


In [44]:
np1[1] = 42
print(f'changed np1:{np1}')
print(f'Original np3:{np3}')

changed np1:[41 42  2  3  4  5]
Original np3:[41  1  2  3  4  5]


In [45]:
# if we change the view it will change the original one
# but in copy the array are not connected in any way

In [5]:
#shape and reshape

a1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a1.shape

(12,)

In [6]:
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2.shape

(2, 5)

In [9]:
#reshapping
a3 = a1.reshape(3,4)
print(a3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
a4 = a1.reshape(2,3,2)
print(a4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
a5 = a2.reshape(-1)
print(a5)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
#iterating in numpy array

np1 = np.array([1,2,3,4,5,6,7,8,9,10])
for x in np1:
    print(x)

1
2
3
4
5
6
7
8
9
10


In [16]:
np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
for x in np2:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10
11
12


In [20]:
#3d array
np3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(np3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [21]:
for x in np3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [22]:
#use np.nditer()

for x in np.nditer(np3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
